name       : ripgrep
version    : 0.7.1
release    : 1
source     :
    - https://github.com/BurntSushi/ripgrep/archive/0.7.1.tar.gz : e010693637acebb409f3dba7caf59ef093d1894a33b14015041b8d43547665f5
license    : MIT
component  : programming.tools
summary    : ripgrep combines the usability of The Silver Searcher with the raw speed of grep
description: |
    ripgrep combines the usability of The Silver Searcher with the raw speed of grep
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm755 target/release/rg $installdir/usr/bin/rg
    install -Dm644 doc/rg.1 $installdir/usr/share/man/man1/rg.1
