name       : ripgrep
version    : 0.10.0
release    : 3
source     :
    - https://github.com/BurntSushi/ripgrep/archive/0.10.0.tar.gz : a2a6eb7d33d75e64613c158e1ae450899b437e37f1bfbd54f713b011cd8cc31e
license    : MIT
component  : programming.tools
summary    : ripgrep combines the usability of The Silver Searcher with the raw speed of grep
description: |
    ripgrep combines the usability of The Silver Searcher with the raw speed of grep
networking : yes
builddeps  :
    - asciidoc
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm755 target/release/rg $installdir/usr/bin/rg
    install -Dm644 complete/_rg $installdir/usr/share/zsh/site-functions/_rg
    install -Dm644 target/release/build/ripgrep-*/out/rg.bash "$installdir/usr/share/bash-completion/completions/rg"
    install -Dm644 target/release/build/ripgrep-*/out/rg.fish "$installdir/usr/share/fish/completions/rg.fish"
    install -Dm644 target/release/build/ripgrep-*/out/rg.1 $installdir/usr/share/man/man1/rg.1
check      : |
    cargo test
