name       : ripgrep
version    : 0.9.0
release    : 2
source     :
    - https://github.com/BurntSushi/ripgrep/archive/0.9.0.tar.gz : 871a24ad29a4c5b6d82f6049156db2662e6a9820cca6f361547b8ab8bc1be7ae
license    : MIT
component  : programming.tools
summary    : ripgrep combines the usability of The Silver Searcher with the raw speed of grep
description: |
    ripgrep combines the usability of The Silver Searcher with the raw speed of grep
networking : yes
builddeps  :
    - asciidoc
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm755 target/release/rg $installdir/usr/bin/rg
    install -Dm644 complete/_rg $installdir/usr/share/zsh/site-functions/_rg
    install -Dm644 target/release/build/ripgrep-*/out/rg.bash "$installdir/usr/share/bash-completion/completions/rg"
    install -Dm644 target/release/build/ripgrep-*/out/rg.fish "$installdir/usr/share/fish/completions/rg.fish"
    install -Dm644 target/release/build/ripgrep-*/out/rg.1 $installdir/usr/share/man/man1/rg.1
