name       : ripgrep
version    : 13.0.0
release    : 13
source     :
    - https://github.com/BurntSushi/ripgrep/archive/refs/tags/13.0.0.tar.gz : 0fb17aaf285b3eee8ddab17b833af1e190d73de317ff9648751ab0660d763ed2
homepage   : https://github.com/BurntSushi/ripgrep
license    : MIT
component  : programming.tools
summary    : ripgrep combines the usability of The Silver Searcher with the raw speed of grep
description: |
    ripgrep is a cross-platform, line-oriented search tool that recursively searches your current directory for a regex pattern. By default, ripgrep will respect your .gitignore and automatically skip hidden files/directories and binary files. ripgrep is similar to other popular search tools like The Silver Searcher, ack and grep.
networking : yes
builddeps  :
    - pkgconfig(libpcre2-posix)
    - asciidoc
    - cargo
build      : |
    cargo build --release --features 'pcre2'
install    : |
    install -Dm00755 target/release/rg $installdir/usr/bin/rg
    install -Dm00644 complete/_rg $installdir/usr/share/zsh/site-functions/_rg
    install -Dm00644 target/release/build/ripgrep-*/out/rg.bash $installdir/usr/share/bash-completion/completions/rg
    install -Dm00644 target/release/build/ripgrep-*/out/rg.fish $installdir/usr/share/fish/vendor_completions.d/rg.fish
    install -Dm00644 target/release/build/ripgrep-*/out/rg.1 $installdir/usr/share/man/man1/rg.1
check      : |
    cargo test --all
