name       : ripgrep
version    : 11.0.1
release    : 4
source     :
    - https://github.com/BurntSushi/ripgrep/archive/11.0.1.tar.gz : ba106404342160a66f703b8c9db9d45117c1a3664a0996822496bcb9f238b184
license    : MIT
component  : programming.tools
summary    : ripgrep combines the usability of The Silver Searcher with the raw speed of grep
description: |
    ripgrep combines the usability of The Silver Searcher with the raw speed of grep
networking : yes
builddeps  :
    - pkgconfig(libpcre2-posix)
    - asciidoc
    - cargo
build      : |
    cargo build --release --features 'pcre2'
install    : |
    install -Dm00755 target/release/rg $installdir/usr/bin/rg
    install -Dm00644 complete/_rg $installdir/usr/share/zsh/site-functions/_rg
    install -Dm00644 target/release/build/ripgrep-*/out/rg.bash "$installdir/usr/share/bash-completion/completions/rg"
    install -Dm00644 target/release/build/ripgrep-*/out/rg.fish "$installdir/usr/share/fish/completions/rg.fish"
    install -Dm00644 target/release/build/ripgrep-*/out/rg.1 $installdir/usr/share/man/man1/rg.1
check      : |
    cargo test --all
